# Generated by Django 4.1.7 on 2023-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='default/no_img.jpg', null=True, upload_to='exam_pic/')),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=30)),
            ],
        ),
    ]
